import type { Metadata } from "next";
import { Inter } from "next/font/google";

import './global.css';
import 'bootstrap/dist/css/bootstrap.min.css';

import SessionAuthProvider from "./context/SessionAuthProvider";

import BarraNavegacion from "@/components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <head>
      </head>
      <body>
        <SessionAuthProvider>
          <BarraNavegacion />
          <main>
            {children}
          </main>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
